//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework3.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfAbstractLocomotive xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;AbstractLocomotive xsi:type=&quot;DiselLocomotive&quot;&gt;
        ///    &lt;ID&gt;0&lt;/ID&gt;
        ///    &lt;LocamativeModel&gt;CastomXML&lt;/LocamativeModel&gt;
        ///    &lt;LocamativeType&gt;Diesel&lt;/LocamativeType&gt;
        ///    &lt;OwnMass&gt;3500&lt;/OwnMass&gt;
        ///    &lt;MaxMass&gt;15800&lt;/MaxMass&gt;
        ///  &lt;/AbstractLocomotive&gt;
        ///  &lt;AbstractLocomotive xsi:type=&quot;ElectroLocomotive&quot;&gt;
        ///    &lt;ID&gt;0&lt;/ID&gt;
        ///    &lt;LocamativeModel&gt;CastomXML&lt;/LocamativeMode [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string locomotives {
            get {
                return ResourceManager.GetString("locomotives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfAbstractRailwayСarriage xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;AbstractRailwayСarriage xsi:type=&quot;ReservedSeatRailwayСarriage&quot;&gt;
        ///    &lt;ID&gt;0&lt;/ID&gt;
        ///    &lt;RailwayСarriageModel&gt;CastomXML&lt;/RailwayСarriageModel&gt;
        ///    &lt;RailwayСarriageType&gt;ReservedSeat&lt;/RailwayСarriageType&gt;
        ///    &lt;OwnMass&gt;1300&lt;/OwnMass&gt;
        ///    &lt;PassengersCount&gt;88&lt;/PassengersCount&gt;
        ///    &lt;ReservedPlaceCount&gt;0&lt;/ReservedPlaceCount&gt;
        ///    &lt;FreePlaceCount&gt;0&lt;/FreePlac [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string railwayСarriages {
            get {
                return ResourceManager.GetString("railwayСarriages", resourceCulture);
            }
        }
    }
}
